config/routes.rb
Portfolio::Application.routes.draw do
  match "/galleries/:shortname" => "galleries#show"
  match "/galleries" => "galleries#index"
  match "/rebuild" => "galleries#rebuild", :via => :get
  match "/rebuild" => "galleries#fetch", :via => :post
  match "/setup" => "galleries#setup", :via => :get
  match "/setup" => "galleries#write_settings", :via => :post

  root :to => "galleries#splash"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy

  validates_uniqueness_of :shortname

  default_scope :order => 'ordering ASC'

  def self.create_from_imgur(gallery_hash, albums=nil)
    albums ||= Imgur.get("account/albums.json")['albums']
    unless album = albums.detect{|a| a['id'] == gallery_hash}
      raise "Album '#{gallery_hash}' not found"
    end

    g = Gallery.create({
      :title        => album['title'],
      :shortname    => album['link'].split('/').last,
      :description  => album['description'],
      :imgur_id     => album['id'],
      :ordering     => album['order']
    })

    images = Imgur.get("account/albums/#{gallery_hash}.json")['albums']
    images.each do |img|
        Picture.create_from_json(g, img)
    end
  end

  def self.rebuild_galleries_from_imgur!
    Gallery.destroy_all
    self.albums.each do |album|
      Gallery.create_from_imgur(album['id'], self.albums)
    end
    Setting.set(:last_rebuilt, Time.now.to_s)
  end

  def self.limited_rebuild!(period)
    last_rebuilt = Setting.get(:last_rebuilt)
    last_rebuilt = Time.parse(last_rebuilt) if last_rebuilt
    if last_rebuilt.blank? or (last_rebuilt + period < Time.now)
      self.rebuild_galleries_from_imgur!
    else
      raise "Cannot rebuild until #{last_rebuilt + period}!"
    end
  end

  def self.albums
    @albums ||= Imgur.get("account/albums.json")['albums'].select do |alb|
      alb and alb['privacy'] and alb['privacy'] == 'public'
    end
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery

  def self.create_from_json(gal, j)
    Picture.create({
      :imgur_id         => j['image']['hash'],
      :caption          => j['image']['caption'],
      :name             => j['image']['title'],
      :width            => j['image']['width'],
      :height           => j['image']['height'],
      :url              => j['links']['original'],
      :thumbnail_url    => j['links']['large_thumbnail'],
      :gallery_id       => gal.id
    })
  end

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates_uniqueness_of :name

  def self.clear!
    Setting.delete_all
  end

  def self.get(name)
    Setting.where(:name => name.to_s).first.try(:value)
  end

  def self.exist?(name)
    Setting.where(:name => name.to_s).count > 0
  end

  def self.set(name, value)
    s = self.find_or_create_by_name(:name => name.to_s)
    s.value = value
    s.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def setup
    if settings_found?
      redirect_to root_path
    end
  end

  def write_settings
    if settings_found?
      raise "reset settings by changing the imgur password"
      redirect_to root_path
    else
      if [params[:username], params[:password], params[:email]].all?{|p| p.present?}
        Setting.set(:username, params[:username])
        Setting.set(:password, params[:password])
        Setting.set(:email,    params[:email]) 

        self.fetch
      else
        redirect_to setup_path
      end
    end
  end

  def splash
    redirect_to(setup_path) unless settings_found?
  end

  def index
    redirect_to(setup_path) unless settings_found?
    @gals = Gallery.all
    @email = Setting.get :email
  end

  def show
    redirect_to(setup_path) unless settings_found?
    @gal = Gallery.find_by_shortname(params[:shortname])
    raise "No gallery found" unless @gal.present?
  end

  def rebuild
    @username = Setting.get :username
    @last_built = Setting.get :last_built
  end

  def fetch
    begin
      Gallery.limited_rebuild! 5.minutes
      redirect_to root_path
    rescue RestClient::BadRequest
      Setting.clear!
      redirect_to root_path
    end
  end


  def settings_found?
    Setting.get(:username).present? and Setting.get(:password).present? and Setting.get(:email).present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
  def gallery_path(gal)
    "/galleries/#{gal.shortname}"
  end
end

app/views/galleries/index.html.haml
%h3 All Galleries

%ol
  - @gals.each do |gal|
    %li= link_to gal.title, gallery_path(gal)
      
= mail_to @email

app/views/galleries/rebuild.html.haml
%h3 Rebuild

%p= "Last built: #{@last_built or 'never'}"
%p= "Rebuild the site from #{@username}.imgur.com?"

= button_to 'Rebuild', :action => "fetch"

app/views/galleries/setup.html.haml
%h3 Setup

= form_tag :action => 'setup' do |f|
  %table
    %tr
      %td username:
      %td= text_field_tag 'username', '', :size => 20, :placeholder => 'imgur username'
    %tr
      %td email:
      %td= text_field_tag 'email',    '', :size => 20, :placeholder => 'email address'
    %tr
      %td password:
      %td= text_field_tag 'password', '', :size => 20, :placeholder => 'imgur password'
    %tr
      %td
      %td= submit_tag 'Build', :confirm => 'Build the site with this imgur account?'

app/views/galleries/show.html.haml
%h3= "Gallery #{@gal.title}"

%ol
  - @gal.pictures.each do |pic|
    %li
      = image_tag pic.url
      %p= pic.caption

app/views/galleries/splash.html.haml
%h3 splash screen!!!!!

= link_to 'main page', galleries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>